//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRendererForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfRendererForm.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Projektfile (XML).
        /// </summary>
        public static string btnAppSaveNew {
            get {
                return ResourceManager.GetString("btnAppSaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration speichern.
        /// </summary>
        public static string btnConfigUebernehmen {
            get {
                return ResourceManager.GetString("btnConfigUebernehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Access-Tabellen.
        /// </summary>
        public static string btnLoadAccessTables {
            get {
                return ResourceManager.GetString("btnLoadAccessTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration laden.
        /// </summary>
        public static string btnLoadConfiguration {
            get {
                return ResourceManager.GetString("btnLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade SQL Server Tabellen.
        /// </summary>
        public static string btnLoadSqlServerTables {
            get {
                return ResourceManager.GetString("btnLoadSqlServerTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVRenderer Update.
        /// </summary>
        public static string btnRenderer {
            get {
                return ResourceManager.GetString("btnRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylefile hinzufügen.
        /// </summary>
        public static string btnStylefileAdd {
            get {
                return ResourceManager.GetString("btnStylefileAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Export.
        /// </summary>
        public static string btnSymbol {
            get {
                return ResourceManager.GetString("btnSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Legendentext verändern.
        /// </summary>
        public static string checkBox1 {
            get {
                return ResourceManager.GetString("checkBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Verwende Access.
        /// </summary>
        public static string chkAccess {
            get {
                return ResourceManager.GetString("chkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   alle sichtbaren Layer rendern.
        /// </summary>
        public static string chkAllLayers {
            get {
                return ResourceManager.GetString("chkAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Use Sql Authentifizierung.
        /// </summary>
        public static string chkAuthentifizierung {
            get {
                return ResourceManager.GetString("chkAuthentifizierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   nur Hintergrundfarben.
        /// </summary>
        public static string chkHintergrund {
            get {
                return ResourceManager.GetString("chkHintergrund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Verwende Sde.
        /// </summary>
        public static string chkSde {
            get {
                return ResourceManager.GetString("chkSde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Deutsch.
        /// </summary>
        public static string chkSpracheDeutsch {
            get {
                return ResourceManager.GetString("chkSpracheDeutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Englisch.
        /// </summary>
        public static string chkSpracheEnglisch {
            get {
                return ResourceManager.GetString("chkSpracheEnglisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   SDE - Legendentabelle.
        /// </summary>
        public static string chkSqlServer {
            get {
                return ResourceManager.GetString("chkSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Optional eine Überschrift verwenden.
        /// </summary>
        public static string chkUeberschrift {
            get {
                return ResourceManager.GetString("chkUeberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   kein Umriss.
        /// </summary>
        public static string chkUmriss {
            get {
                return ResourceManager.GetString("chkUmriss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungseigenschaften:.
        /// </summary>
        public static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretierte Schmuckfarben in %.
        /// </summary>
        public static string groupBox2 {
            get {
                return ResourceManager.GetString("groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string grpEinstellungen {
            get {
                return ResourceManager.GetString("grpEinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessDB:.
        /// </summary>
        public static string lblAccessdatenbank {
            get {
                return ResourceManager.GetString("lblAccessdatenbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - BLAU:.
        /// </summary>
        public static string lblAufdruckBlau {
            get {
                return ResourceManager.GetString("lblAufdruckBlau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - BRAUN:.
        /// </summary>
        public static string lblAufdruckBraun {
            get {
                return ResourceManager.GetString("lblAufdruckBraun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - CYAN:.
        /// </summary>
        public static string lblAufdruckCyan {
            get {
                return ResourceManager.GetString("lblAufdruckCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - GELB:.
        /// </summary>
        public static string lblAufdruckGelb {
            get {
                return ResourceManager.GetString("lblAufdruckGelb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - GRAU:.
        /// </summary>
        public static string lblAufdruckGrau {
            get {
                return ResourceManager.GetString("lblAufdruckGrau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - GRÜN:.
        /// </summary>
        public static string lblAufdruckGruen {
            get {
                return ResourceManager.GetString("lblAufdruckGruen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - MAGENTA:.
        /// </summary>
        public static string lblAufdruckMagenta {
            get {
                return ResourceManager.GetString("lblAufdruckMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - ORANGE:.
        /// </summary>
        public static string lblAufdruckOrange {
            get {
                return ResourceManager.GetString("lblAufdruckOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - ROT:.
        /// </summary>
        public static string lblAufdruckRot {
            get {
                return ResourceManager.GetString("lblAufdruckRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank:.
        /// </summary>
        public static string lblDatabase {
            get {
                return ResourceManager.GetString("lblDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feld 1:.
        /// </summary>
        public static string lblFeld1 {
            get {
                return ResourceManager.GetString("lblFeld1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feld 2:.
        /// </summary>
        public static string lblFeld2 {
            get {
                return ResourceManager.GetString("lblFeld2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flächensymbolname:.
        /// </summary>
        public static string lblFlaeche {
            get {
                return ResourceManager.GetString("lblFlaeche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instanz:.
        /// </summary>
        public static string lblInstance {
            get {
                return ResourceManager.GetString("lblInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsdatei:.
        /// </summary>
        public static string lblKonfigurationsdatei {
            get {
                return ResourceManager.GetString("lblKonfigurationsdatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layername:.
        /// </summary>
        public static string lblLayername {
            get {
                return ResourceManager.GetString("lblLayername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendentabelle:.
        /// </summary>
        public static string lblLegendentabelle {
            get {
                return ResourceManager.GetString("lblLegendentabelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liniensymbolname:.
        /// </summary>
        public static string lblLinie {
            get {
                return ResourceManager.GetString("lblLinie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markersymbolname:.
        /// </summary>
        public static string lblMarker {
            get {
                return ResourceManager.GetString("lblMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort:.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurations File.
        /// </summary>
        public static string lblProjectfile {
            get {
                return ResourceManager.GetString("lblProjectfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string lblServer {
            get {
                return ResourceManager.GetString("lblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortierspalte:.
        /// </summary>
        public static string lblSortierspalte {
            get {
                return ResourceManager.GetString("lblSortierspalte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwende ein Style File aus der ArcMap-StyleStorage:.
        /// </summary>
        public static string lblStyle {
            get {
                return ResourceManager.GetString("lblStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Symbol Style:.
        /// </summary>
        public static string lblStylefile {
            get {
                return ResourceManager.GetString("lblStylefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie bitte ein Stylefile:.
        /// </summary>
        public static string lblStylefileLabel1 {
            get {
                return ResourceManager.GetString("lblStylefileLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylefile:.
        /// </summary>
        public static string lblStylefileLabel2 {
            get {
                return ResourceManager.GetString("lblStylefileLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolexportordner:.
        /// </summary>
        public static string lblSymbolDirectory {
            get {
                return ResourceManager.GetString("lblSymbolDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie bitte einen Ordner für den Image Export:.
        /// </summary>
        public static string lblSymbolLabel {
            get {
                return ResourceManager.GetString("lblSymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennzeichen:.
        /// </summary>
        public static string lblTrennzeichen {
            get {
                return ResourceManager.GetString("lblTrennzeichen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift:.
        /// </summary>
        public static string lblUeberschrift {
            get {
                return ResourceManager.GetString("lblUeberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verknüpfungs ID:.
        /// </summary>
        public static string lblVerknuepfung {
            get {
                return ResourceManager.GetString("lblVerknuepfung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string lblVersion {
            get {
                return ResourceManager.GetString("lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string mnuAppAbout {
            get {
                return ResourceManager.GetString("mnuAppAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung schließen.
        /// </summary>
        public static string mnuAppClose {
            get {
                return ResourceManager.GetString("mnuAppClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureRenderer-Hilfe.
        /// </summary>
        public static string mnuAppHelp {
            get {
                return ResourceManager.GetString("mnuAppHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsfile öffnen.
        /// </summary>
        public static string mnuAppLoad {
            get {
                return ResourceManager.GetString("mnuAppLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei speichern.
        /// </summary>
        public static string mnuAppSave {
            get {
                return ResourceManager.GetString("mnuAppSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei speichern unter.
        /// </summary>
        public static string mnuAppSaveNew {
            get {
                return ResourceManager.GetString("mnuAppSaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankeinstellungen.
        /// </summary>
        public static string mnuDatenbankeinstellungen {
            get {
                return ResourceManager.GetString("mnuDatenbankeinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string mnuEinstellungen {
            get {
                return ResourceManager.GetString("mnuEinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string mnuHilfe {
            get {
                return ResourceManager.GetString("mnuHilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string mnuInfo {
            get {
                return ResourceManager.GetString("mnuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Export.
        /// </summary>
        public static string mnuLayerExport {
            get {
                return ResourceManager.GetString("mnuLayerExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylefile laden.
        /// </summary>
        public static string mnuLoadStylefile {
            get {
                return ResourceManager.GetString("mnuLoadStylefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige XML File.
        /// </summary>
        public static string mnuShowXml {
            get {
                return ResourceManager.GetString("mnuShowXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spracheinstellungen.
        /// </summary>
        public static string mnuSpracheinstellungen {
            get {
                return ResourceManager.GetString("mnuSpracheinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol export.
        /// </summary>
        public static string mnuSymbolExport {
            get {
                return ResourceManager.GetString("mnuSymbolExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungseinstellungen.
        /// </summary>
        public static string mnuVerbindung {
            get {
                return ResourceManager.GetString("mnuVerbindung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Datenbank.
        /// </summary>
        public static string tabItemAccess {
            get {
                return ResourceManager.GetString("tabItemAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankspalten.
        /// </summary>
        public static string tabItemDatabase {
            get {
                return ResourceManager.GetString("tabItemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optionale Datenbankspalten.
        /// </summary>
        public static string tabItemDatabaseOptional {
            get {
                return ResourceManager.GetString("tabItemDatabaseOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDE Datenbank.
        /// </summary>
        public static string tabItemSde {
            get {
                return ResourceManager.GetString("tabItemSde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureRenderer für ArcMap 10.0.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
